export enum FileStatus {
    // LINK_REQUEST = 'LINK_REQUEST',
    // PULL_FROM_SYSTEM = 'PULL_FROM_SYSTEM',
    // START_STRAIGHT = 'START_STRAIGHT',
    // SENT_TO_GOOGLE = 'SENT_TO_GOOGLE',
    // START_LOGIC = 'SENT_TO_GOOGLE',
    // FINISHED_LOGIC = 'FINISHED_LOGIC',

    WAIT_FOR_CONFIRM = 'WAIT_FOR_CONFIRM',
    CREATE_HASH_BANK = 'CREATE_HASH_BANK',
    CREATE_JOURNAL_TRANS = 'CREATE_JOURNAL_TRANS',

    ARCHIVE = 'ARCHIVE',
    // DELETED = 'DELETED',
    WAIT_FOR_CARE = 'WAIT_FOR_CARE'
}
